# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'inapp-voice' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for inapp-voice
  pod 'VonageClientSDKVoice', '1.0.3-rc.0'
  pod 'Firebase/Messaging'
end
